# Generated by Django 3.1.12 on 2022-05-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20220505_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='profile',
        ),
    ]
