# Generated by Django 3.1.12 on 2022-06-03 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_recent_played_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='played_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
