# Generated by Django 3.1.12 on 2022-06-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20220603_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recent',
            old_name='played_time',
            new_name='played_at',
        ),
    ]
