# Generated by Django 3.1.12 on 2022-06-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_auto_20220620_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='songs',
        ),
    ]
