# Generated by Django 3.1.12 on 2022-06-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_auto_20220620_0027'),
        ('musicapp', '0010_auto_20220621_1809'),
    ]

    operations = [
    ]
