# Generated by Django 3.1.12 on 2022-06-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_remove_genre_songs'),
        ('musicapp', '0010_auto_20220621_1809'),
    ]

    operations = [
    ]
