# Generated by Django 3.1.12 on 2022-06-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_merge_20220622_0032'),
        ('musicapp', '0012_merge_20220622_0339'),
    ]

    operations = [
    ]
