# Generated by Django 3.1.12 on 2022-06-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_merge_20220622_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='media/playlist'),
        ),
    ]
